# ==========================================
# CONEXIÓN A SQL SERVER CON AUTENTICACIÓN INTEGRADA (WINDOWS)
# ==========================================

# Se agrega integratedSecurity=true para omitir usuario y contraseña
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=miTienda;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Silenciar advertencia de Open Session In View
spring.jpa.open-in-view=false

# ==========================================
# CONFIGURACIÓN DE ARCHIVOS
# ==========================================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
